# Generated by Django 5.0.4 on 2024-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
