# Generated by Django 5.0.6 on 2024-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.CharField(max_length=255),
        ),
    ]
